# -*- coding: utf-8 -*-
"""score predictor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LgcjsXKeJJHPESaKwLfLZ5X1V4SZS2Vc
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
dipam7_student_grade_prediction_path = kagglehub.dataset_download('dipam7/student-grade-prediction')

print('Data source import complete.')

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

data = pd.read_csv('/kaggle/input/student-grade-prediction/student-mat.csv')

data.head()

data.info()

data.drop(columns=['school','sex','address','famsize','Pstatus','Medu','Fedu','Mjob','Fjob','reason','guardian','traveltime','schoolsup','famsup','paid','nursery','higher','internet','romantic','freetime','goout','Dalc','Walc','failures','activities','G2','G3'], inplace=True)

data.describe

data.isna().any()

data.columns = ['age','studytime','famrel','health','absences','G1']

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
!pip install catboost
from catboost import CatBoostRegressor
from sklearn.linear_model import LinearRegression

X = data.values[:,:-1]
Y = data.values[:,-1]

X_train , X_test, Y_train , Y_test = train_test_split(X, Y, test_size = 0.2)

model = CatBoostRegressor()
model.fit(X_train, Y_train)

prediction = model.predict(X_test)
print(mean_absolute_error(Y_test, prediction))

model.fit(X, Y)

def get_int_input(prompt):
  """Asks the user for an integral value repeatedly until a valid integer is provided.

  Args:
    prompt: The prompt to display to the user.

  Returns:
    The integer entered by the user.
  """
  while True:
    try:
      value = int(input(prompt))
      return value
    except ValueError:
      print("Invalid input. Please enter an integer.")
def ask_boolean_input(question):
    """Asks the user a yes/no question and returns a boolean value.

    Args:
        question: The question to ask the user.

    Returns:
        True if the user answers "yes" (or any variation thereof),
        False otherwise.
    """
    while True:
        user_input = input(f"{question} (yes/no): ").strip().lower()
        if user_input in ["yes", "y"]:
            return True
        elif user_input in ["no", "n"]:
            return False
        else:
            print("Invalid input. Please enter 'yes' or 'no'.")
import numpy as np
def predict_score(age, studytime, famrel, health, absences):
    """Predicts the G1 score based on the input features.

    Args:
      age: The age of the student.
      studytime: The weekly study time.
      famrel: Quality of family relationships.
      health: Current health status.
      absences: Number of school absences.

    Returns:
      The predicted G1 score.
    """

    # Create a NumPy array with the input features
    input_data = np.array([[age, studytime, famrel, health, absences]])

    # Make the prediction using the pre-trained model (assuming 'model' is defined elsewhere)
    predicted_score = model.predict(input_data)

    return predicted_score[0]

# Get user inputs
age = get_int_input("What is your age (15-22): ")
studytime = get_int_input("What is your weekly study time (1-4): ")
famrel = get_int_input("How good is your family relationship (1-5): ")
health = get_int_input("How good is your health (1-5): ")
absences = get_int_input("What were your absences (0-75): ")


# Predict and print the score
predicted_g1 = predict_score(age, studytime, famrel, health, absences)
print(f"Predicted G1 score: {predicted_g1}")